# Generated by Django 6.0.4 on 2026-04-17 06:45

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def populate_published_at_from_created_at(apps, schema_editor):
    News = apps.get_model('news', 'News')
    News.objects.all().update(published_at=F('created_at'))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsimage_newsvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AddField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.RunPython(
            code=populate_published_at_from_created_at,
            reverse_code=noop_reverse,
        ),
    ]
