# Generated by Django 6.0.4 on 2026-04-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=500)),
                ('address_uz', models.CharField(max_length=500, null=True)),
                ('address_en', models.CharField(max_length=500, null=True)),
                ('address_fr', models.CharField(max_length=500, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('working_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('working_hours_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('working_hours_en', models.CharField(blank=True, max_length=255, null=True)),
                ('working_hours_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('map_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('icon', models.FileField(blank=True, null=True, upload_to='social_icons/')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
            },
        ),
    ]
