# Generated by Django 6.0.4 on 2026-04-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': "Kontakt ma'lumoti", 'verbose_name_plural': "Kontakt ma'lumotlari"},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'Ijtimoiy tarmoq', 'verbose_name_plural': 'Ijtimoiy tarmoqlar'},
        ),
    ]
