# Generated by Django 6.0.4 on 2026-04-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Kafedra', 'verbose_name_plural': 'Kafedralar'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Fakultet', 'verbose_name_plural': 'Fakultetlar'},
        ),
    ]
