# Generated by Django 6.0.4 on 2026-04-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Universitet tarixi', 'verbose_name_plural': 'Universitet tarixi'},
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'Statik sahifa', 'verbose_name_plural': 'Statik sahifalar'},
        ),
    ]
