# Generated by Django 6.0.4 on 2026-04-15 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_slider_slideritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='slideritem',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='slideritem',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='slideritem',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='slideritem',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='slideritem',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='slideritem',
            name='title_uz',
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='slider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='common.slider'),
        ),
    ]
