# Generated by Django 6.0.4 on 2026-04-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_slider_title_en_remove_slider_title_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideritem',
            name='image',
            field=models.ImageField(blank=True, help_text="Rasm fayl yuklang. Agar fayl bo'lmasa, pastdagi Image URL ni kiriting.", null=True, upload_to='sliders/'),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='link',
            field=models.URLField(blank=True, help_text='Tashqi rasm URL manzili (https://...).', null=True, verbose_name='Image URL'),
        ),
    ]
