# Generated by Django 6.0.4 on 2026-04-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_slideritem_image_alter_slideritem_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='category_en',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='category_fr',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='category_uz',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='media_file',
            field=models.FileField(blank=True, help_text="Qo'shimcha media fayl yuklang (masalan, video). Agar fayl bo'lmasa, pastdagi Media URL ni kiriting.", null=True, upload_to='sliders/media/'),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='link',
            field=models.URLField(blank=True, help_text='Tashqi media URL manzili (https://...).', null=True, verbose_name='Media URL'),
        ),
    ]
