# Generated by Django 6.0.4 on 2026-04-20 07:20

import django.db.models.deletion
from django.db import migrations, models


def create_slider_category_table_if_missing(apps, schema_editor):
    """Conditionally create SliderCategory table"""
    table_name = 'common_slidercategory'
    if table_name in schema_editor.connection.introspection.table_names():
        return

    vendor = schema_editor.connection.vendor
    cursor = schema_editor.connection.cursor()
    if vendor == 'postgresql':
        cursor.execute('''
            CREATE TABLE common_slidercategory (
                id BIGSERIAL PRIMARY KEY,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                name VARCHAR(120) NOT NULL,
                name_uz VARCHAR(120),
                name_en VARCHAR(120),
                name_fr VARCHAR(120),
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                "order" INTEGER NOT NULL DEFAULT 0
            )
        ''')
    else:
        cursor.execute('''
            CREATE TABLE common_slidercategory (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                name VARCHAR(120) NOT NULL,
                name_uz VARCHAR(120),
                name_en VARCHAR(120),
                name_fr VARCHAR(120),
                is_active BOOLEAN NOT NULL DEFAULT 1,
                "order" INTEGER NOT NULL DEFAULT 0
            )
        ''')


def add_slideritem_category_column_if_missing(apps, schema_editor):
    """Conditionally add category_ref_id column to SliderItem"""
    cursor = schema_editor.connection.cursor()
    table_name = 'common_slideritem'
    vendor = schema_editor.connection.vendor
    
    columns = {
        column_info.name
        for column_info in (
            schema_editor.connection.introspection.get_table_description(
                cursor,
                table_name,
            )
        )
    }
    
    #  Add the category_ref_id FK column if it doesn't exist
    # (SQLite will automatically allow its existence even if old category exists)
    if 'category_ref_id' not in columns:
        if vendor == 'postgresql':
            cursor.execute(f'''
                ALTER TABLE {table_name}
                ADD COLUMN category_ref_id BIGINT NULL
                    REFERENCES common_slidercategory(id)
            ''')
        else:
            # Add nullable FK column
            cursor.execute(f'''
                ALTER TABLE {table_name}
                ADD COLUMN category_ref_id INTEGER NULL
                    REFERENCES common_slidercategory(id)
            ''')


def create_slider_media_table_if_missing(apps, schema_editor):
    """Conditionally create SliderMedia table"""
    table_name = 'common_slidermedia'
    if table_name in schema_editor.connection.introspection.table_names():
        return

    vendor = schema_editor.connection.vendor
    cursor = schema_editor.connection.cursor()
    if vendor == 'postgresql':
        cursor.execute('''
            CREATE TABLE common_slidermedia (
                id BIGSERIAL PRIMARY KEY,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                slider_item_id BIGINT NOT NULL REFERENCES common_slideritem(id),
                media_type VARCHAR(16) NOT NULL DEFAULT 'image',
                file VARCHAR(100) NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                "order" INTEGER NOT NULL DEFAULT 0
            )
        ''')
    else:
        cursor.execute('''
            CREATE TABLE common_slidermedia (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                slider_item_id INTEGER NOT NULL REFERENCES common_slideritem(id),
                media_type VARCHAR(16) NOT NULL DEFAULT 'image',
                file VARCHAR(100) NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT 1,
                "order" INTEGER NOT NULL DEFAULT 0
            )
        ''')


class Migration(migrations.Migration):

    dependencies = [
        (
            'common',
            '0006_slider_title_en_slider_title_fr_slider_title_uz_and_more',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_slider_category_table_if_missing,
                    migrations.RunPython.noop,
                ),
                migrations.RunPython(
                    add_slideritem_category_column_if_missing,
                    migrations.RunPython.noop,
                ),
                migrations.RunPython(
                    create_slider_media_table_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='SliderCategory',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        (
                            'created_at',
                            models.DateTimeField(auto_now_add=True),
                        ),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=120)),
                        (
                            'name_uz',
                            models.CharField(max_length=120, null=True),
                        ),
                        (
                            'name_en',
                            models.CharField(max_length=120, null=True),
                        ),
                        (
                            'name_fr',
                            models.CharField(max_length=120, null=True),
                        ),
                        ('is_active', models.BooleanField(default=True)),
                        ('order', models.PositiveIntegerField(default=0)),
                    ],
                    options={
                        'verbose_name': 'Slider kategoriyasi',
                        'verbose_name_plural': 'Slider kategoriyalari',
                        'ordering': ['order', 'id'],
                    },
                ),
                migrations.AddField(
                    model_name='slideritem',
                    name='category',
                    field=models.ForeignKey(
                        blank=True,
                        db_column='category_ref_id',
                        null=True,
                        on_delete=models.SET_NULL,
                        related_name='slider_items',
                        to='common.slidercategory',
                    ),
                ),
                migrations.CreateModel(
                    name='SliderMedia',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        (
                            'created_at',
                            models.DateTimeField(auto_now_add=True),
                        ),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        (
                            'media_type',
                            models.CharField(
                                choices=[
                                    ('image', 'Image'),
                                    ('video', 'Video'),
                                ],
                                default='image',
                                max_length=16,
                            ),
                        ),
                        (
                            'file',
                            models.FileField(
                                blank=True,
                                null=True,
                                upload_to='sliders/media/',
                            ),
                        ),
                        ('is_active', models.BooleanField(default=True)),
                        ('order', models.PositiveIntegerField(default=0)),
                        (
                            'slider_item',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='media_items',
                                to='common.slideritem',
                            ),
                        ),
                    ],
                    options={
                        'verbose_name': 'Slider media',
                        'verbose_name_plural': 'Slider medialar',
                        'ordering': ['order', 'id'],
                    },
                ),
            ],
        ),
    ]
