# Generated by Django 6.0.4 on 2026-04-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_slider_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideritem',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='slideritem',
            name='category_fr',
        ),
        migrations.RemoveField(
            model_name='slideritem',
            name='category_uz',
        ),
        migrations.RemoveField(
            model_name='slideritem',
            name='link',
        ),
        migrations.RemoveField(
            model_name='slideritem',
            name='media_file',
        ),
    ]
