# Generated by Django 6.0.4 on 2026-05-12 05:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('passport_series', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message="Passport seriyasi aynan 2 ta harfdan iborat bo'lishi kerak.", regex='^[A-Za-z]{2}$')])),
                ('passport_number', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Passport raqami aynan 7 xonali raqam bo'lishi kerak.", regex='^\\d{7}$')])),
                ('phone_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Telefon raqami + belgisi bilan yoki belgisiz 9 dan 15 tagacha raqamdan iborat bo'lishi kerak.", regex='^\\+?\\d{9,15}$')])),
            ],
            options={
                'verbose_name': 'Talaba arizasi',
                'verbose_name_plural': 'Talaba arizalari',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDiploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='admissions/diplomas/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='admissions.studentapplication')),
            ],
            options={
                'verbose_name': 'Diplom hujjati',
                'verbose_name_plural': 'Diplom hujjatlari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='admissions/certificates/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='admissions.studentapplication')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['id'],
            },
        ),
    ]
