# Generated by Django 6.0.4 on 2026-05-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_studentapplication_review_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='application_pdf',
            field=models.FileField(blank=True, null=True, upload_to='admissions/application_forms/'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='diploma_supplement_file',
            field=models.FileField(blank=True, null=True, upload_to='admissions/diploma_supplements/'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='passport_file',
            field=models.FileField(blank=True, null=True, upload_to='admissions/passports/'),
        ),
    ]
