# Generated by Django 6.0.4 on 2026-05-13 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_studentapplication_application_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='application_pdf',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='diploma_supplement_file',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='passport_file',
        ),
        migrations.CreateModel(
            name='ApplicationDiplomaSupplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='admissions/diploma_supplements/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diploma_supplements', to='admissions.studentapplication')),
            ],
            options={
                'verbose_name': 'Diplom ilovasi fayli',
                'verbose_name_plural': 'Diplom ilovasi fayllari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPassportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='admissions/passports/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_files', to='admissions.studentapplication')),
            ],
            options={
                'verbose_name': 'Passport fayli',
                'verbose_name_plural': 'Passport fayllari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='admissions/application_forms/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_pdfs', to='admissions.studentapplication')),
            ],
            options={
                'verbose_name': 'Ariza PDF hujjati',
                'verbose_name_plural': 'Ariza PDF hujjatlari',
                'ordering': ['id'],
            },
        ),
    ]
