# Generated by Django 6.0.4 on 2026-06-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_remove_studentapplication_application_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
