# Generated by Django 6.0.4 on 2026-06-23 05:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_add_email_to_student_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email manzil'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='middle_name',
            field=models.CharField(max_length=100, verbose_name='Otasining ismi'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='passport_number',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Passport raqami aynan 7 xonali raqam bo'lishi kerak.", regex='^\\d{7}$')], verbose_name='Pasport raqami'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='passport_series',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message="Passport seriyasi aynan 2 ta harfdan iborat bo'lishi kerak.", regex='^[A-Za-z]{2}$')], verbose_name='Pasport seriyasi'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Telefon raqami + belgisi bilan yoki belgisiz 9 dan 15 tagacha raqamdan iborat bo'lishi kerak.", regex='^\\+?\\d{9,15}$')], verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='review_note',
            field=models.TextField(blank=True, verbose_name="Ko'rib chiqish izohi"),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan vaqt"),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_applications', to=settings.AUTH_USER_MODEL, verbose_name="Ko'rib chiqqan xodim"),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], db_index=True, default='pending', max_length=20, verbose_name='Holat'),
        ),
    ]
