# Generated by Django 6.0.4 on 2026-06-23 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_add_verbose_names_to_student_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdiplomasupplement',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationpassportfile',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationpdf',
            name='application',
        ),
        migrations.AlterModelOptions(
            name='applicationdiploma',
            options={'ordering': ['id'], 'verbose_name': 'Universitet diplomi', 'verbose_name_plural': 'Universitet diplomlari'},
        ),
        migrations.AlterField(
            model_name='applicationdiploma',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='admissions.studentapplication', verbose_name='Ariza'),
        ),
        migrations.AlterField(
            model_name='applicationdiploma',
            name='file',
            field=models.FileField(upload_to='admissions/diplomas/', verbose_name='Fayl'),
        ),
        migrations.CreateModel(
            name='ApplicationCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='admissions/cvs/', verbose_name='Fayl')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='admissions.studentapplication', verbose_name='Ariza')),
            ],
            options={
                'verbose_name': 'Tarjima hol',
                'verbose_name_plural': 'Tarjima hollar',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationIdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='admissions/identity_documents/', verbose_name='Fayl')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_documents', to='admissions.studentapplication', verbose_name='Ariza')),
            ],
            options={
                'verbose_name': 'Shaxsni tasdiqlovchi hujjat',
                'verbose_name_plural': 'Shaxsni tasdiqlovchi hujjatlar',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationLanguageCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='admissions/language_certificates/', verbose_name='Fayl')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_certificates', to='admissions.studentapplication', verbose_name='Ariza')),
            ],
            options={
                'verbose_name': 'Til sertifikati',
                'verbose_name_plural': 'Til sertifikatlari',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationMotivationLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='admissions/motivation_letters/', verbose_name='Fayl')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivation_letters', to='admissions.studentapplication', verbose_name='Ariza')),
            ],
            options={
                'verbose_name': 'Motivatsion xat',
                'verbose_name_plural': 'Motivatsion xatlar',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='admissions/transcripts/', verbose_name='Fayl')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='admissions.studentapplication', verbose_name='Ariza')),
            ],
            options={
                'verbose_name': 'Baholar varaqasi',
                'verbose_name_plural': 'Baholar varaqlari',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ApplicationCertificate',
        ),
        migrations.DeleteModel(
            name='ApplicationDiplomaSupplement',
        ),
        migrations.DeleteModel(
            name='ApplicationPassportFile',
        ),
        migrations.DeleteModel(
            name='ApplicationPdf',
        ),
    ]
